export const IMG_CDN_URL =  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_6600/" ;
export const FETCH_RESTO_DETAILS_URL = "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=21.99740&lng=79.00110&restaurantId=658210&catalog_qa=undefined&submitAction=ENTER";
export const FETCH_RESTO_URL = "https://www.swiggy.com/dapi/restaurants/list/v5?lat=21.99740&lng=79.00110&is-seo-homepage-enabled=true&page_type=DESKTOP_WEB_LISTING";
export const restoData = [
    {
      info: {
        id: "509851",
        name: "Magic Momo",
        cloudinaryImageId: "dh0qsuqritnmbncwrni3",
        locality: "Parasia Road",
        areaName: "Prasia Road",
        cuisines: ["Momos", "Chinese"],
        avgRatingString: "3.9",
        totalRatingsString: "41",
      },
    },
    {
      info: {
        id: "774546",
        name: "Shree Naivedyam",
        cloudinaryImageId: "2274f59cb8efcfab1f446b195bcbda3b",
        locality: "Khajri Road",
        areaName: "Chhindwara City",
        costForTwo: "₹300 for two",
        cuisines: [
          "North Indian",
          "Chinese",
          "South Indian",
          "Pizzas",
          "Beverages",
        ],
        avgRating: 4.1,
        veg: true,
        avgRatingString: "4.1",
        totalRatingsString: "89",
      },
    },
    {
      info: {
        id: "658210",
        name: "The Fusion Lounge",
        cloudinaryImageId: "fa4944f0cfdcbca2bec1f3ab8e3db3f7",
        locality: "Triloki nagar",
        areaName: "Railway Station",
        costForTwo: "₹300 for two",
        cuisines: [
          "North Indian",
          "South Indian",
          "Chinese",
          "Beverages",
          "Fast Food",
          "Desserts",
        ],
        avgRating: 4.1,
        avgRatingString: "4.1",
        totalRatingsString: "293",
      },
    },
    {
      info: {
        id: "151518",
        name: "Bakery World",
        cloudinaryImageId: "mt2aggiscfl3yviatwng",
        locality: "Parasia Road",
        areaName: "Parasia Road",
        costForTwo: "₹250 for two",
        cuisines: ["Bakery", "Ice Cream", "Snacks", "Beverages"],
        avgRating: 4.3,
        veg: true,
        avgRatingString: "4.3",
        totalRatingsString: "248",
      },
    },
    {
      info: {
        id: "385824",
        name: "The Belgian Waffle Co.",
        cloudinaryImageId:
          "RX_THUMBNAIL/IMAGES/VENDOR/2024/12/23/246bf7fc-daca-4e63-8a1d-be6f3dccd3fc_385824.JPG",
        locality: "Sinchai Colony",
        areaName: "Mohan Nagar",
        costForTwo: "₹200 for two",
        cuisines: ["Waffle", "Desserts", "Ice Cream", "Beverages"],
        avgRating: 4.7,
        veg: true,
        avgRatingString: "4.7",
        totalRatingsString: "292",
      },
    },
    {
      info: {
        id: "151649",
        name: "Hotel Sai Nath & Sai Restaurant",
        cloudinaryImageId: "vkhcohhmqfczycw9vsar",
        locality: "railway station",
        areaName: "Chhindwara Locality",
        costForTwo: "₹200 for two",
        cuisines: [
          "North Indian",
          "South Indian",
          "Chinese",
          "Beverages",
          "Fast Food",
          "Desserts",
        ],
        avgRating: 4.2,
        veg: true,
        avgRatingString: "4.2",
        totalRatingsString: "934",
      },
    },
    {
      info: {
        id: "599234",
        name: "28 Spice Club",
        cloudinaryImageId: "510fc7e0a265c4c71ef10f0406583373",
        locality: "Shivam Sundaram Colony",
        areaName: "Chhindwara City",
        costForTwo: "₹125 for two",
        cuisines: [
          "North Indian",
          "South Indian",
          "Chinese",
          "Beverages",
          "Fast Food",
          "Desserts",
        ],
        avgRating: 4.4,
        veg: true,
        avgRatingString: "4.4",
        totalRatingsString: "241",
      },
    },
    {
      info: {
        id: "898041",
        name: "Thikana",
        cloudinaryImageId:
          "RX_THUMBNAIL/IMAGES/VENDOR/2024/5/26/78517964-20dc-4e37-92ce-8990deb14ab6_898041.jpg",
        locality: "RANGLA PUNJAB PARASIA ROAD",
        areaName: " ADARSH NAGAR CHHINDWARA",
        costForTwo: "₹250 for two",
        cuisines: ["Indian"],
        avgRating: 4.5,
        avgRatingString: "4.5",
        totalRatingsString: "10",
      },
    },
  ];